version: "3"

services:
  api:
    build:
      context: ./api
    ports:
      - 5000:5000
    env_file:
      - ./.env  # Path to your .env file in the parent directory
    volumes:
      - ./fine-tune/cropped:/images
      - ./masks:/masks
      - ./embeddings:/embeddings
      - ./masks.json:/masks.json
      - ./models:/app/models
      - ./metrics:/metrics
  ui:
    build:
      context: ./ui
    ports:
      - 3000:80
    volumes:
      - ./masks.json:/app/public/masks.json
      - ./.env:/app/.env
    env_file:
      - ./.env  # Path to your .env file in the parent directory